library("data.table")
library("dplyr")
library("ggplot2")
library("stringr")
library("arules")
library("arulesViz")
library("kernlab")

setwd("~/IDS2016/trend")
vsrlist <- fread("vsrlist.csv")

v <- vsrlist %>% select(Model,HA,MH,LB,IDS,ADS,VC,UF,L7)
index <- sample(nrow(v),300)
v.test <- v[index,]
v.train <- v[-index,]
v.classifier <- ksvm(Model ~ ., data = v.train, kernel = "vanilladot")
v.pred <- predict(v.classifier, v.test)
table(v.pred, v.test$Model)

library("neuralnet")
v.classifier <- neuralnet(Model ~ HA+MH+LB+IDS+ADS+VC+UF+L7,
                          data=v.train)
plot(v.classifier)
#v.result <- compute(v.classifier,v.test)
#v.pred <- v.result$net.result
#cor(v.pred,v.sample$Model)

v.classifier <- neuralnet(Model ~ HA+MH+LB+IDS+ADS+VC+UF+L7,
                          data=v.train, hidden=3)
plot(v.classifier)
#v.sample <- v.test[1:10,c("HA","MH","LB","IDS","ADS","VC","UF","L7")]
#v.result <- compute(v.classifier,v.sample)
#v.pred <- v.result$net.result
#cor(v.pred,v.sample$Model)

setwd("~/IDS2016/trigger")
t <- fread("troubles.csv")
t$Time <- as.POSIXct(t$Time,format="%Y/%m/%d %H:%M")
t$Type <- as.factor(t$Type)
t$Trigger <- as.factor(t$Trigger)
t$Replace <- as.factor(t$Replace)
t$BootCount <- as.numeric(t$BootCount)
trouble <- t %>% select(Hostname,Type,Replace,Trigger,BootCount) 

z <- as.data.table(full_join(vsrlist,trouble,by="Hostname"))
z$Model <- as.factor(z$Model)
z$OS <- as.factor(z$OS)
z <- z %>% mutate(Boot = ifelse(is.na(BootCount),0,BootCount))

z.dt <- z %>% select(BR,NAT,VPN,HA,MH,LB,IDS,ADS,PPTP,L2TP,VC,VCWEB,UF,Boot) %>% filter(!is.na(BR))
index <- sample(nrow(z.dt),500)
z.dt.test <- z.dt[index,]
z.dt.train <- z.dt[-index,]
z.classifier <- ksvm(Boot ~ ., data = z.dt.train, kernel = "vanilladot")
z.pred <- predict(z.classifier, z.dt.test)
head(z.pred)
table(z.pred, z.dt.test$Boot)
z.classifier <- neuralnet(BootCount ~ BR+NAT+VPN+HA+MH+LB+IDS+ADS+PPTP+L2TP+VC+VCWEB+UF,
                          data=z.dt.train)
plot(z.classifier)
z.test <- z.dt.test[1:10,c("BR","NAT","VPN","HA","MH","LB","IDS","ADS","PPTP","L2TP","VC","VCWEB","UF")]
z.result <- compute(z.classifier,z.test)
z.pred <- z.result$net.result
cor(z.pred,z.test$BootCount)

trend <- data.table()
for(f in list.files(pattern = "*-20160401.csv")){
  test <- fread(f);
  trend <- rbind(trend,test,fill=T)
}

trend <- trend %>% rename(eth0_in_bytes = `net.if.in[eth0_bytes]`)
trend <- trend %>% rename(eth1_in_bytes = `net.if.in[eth1_bytes]`)
trend <- trend %>% rename(eth2_in_bytes = `net.if.in[eth2_bytes]`)
trend <- trend %>% rename(eth3_in_bytes = `net.if.in[eth3_bytes]`)
trend <- trend %>% rename(eth4_in_bytes = `net.if.in[eth4_bytes]`)
trend <- trend %>% rename(eth5_in_bytes = `net.if.in[eth5_bytes]`)
trend <- trend %>% rename(eth6_in_bytes = `net.if.in[eth6_bytes]`)
trend <- trend %>% rename(eth7_in_bytes = `net.if.in[eth7_bytes]`)
trend <- trend %>% rename(eth8_in_bytes = `net.if.in[eth8_bytes]`)
trend <- trend %>% rename(eth9_in_bytes = `net.if.in[eth9_bytes]`)
trend <- trend %>% rename(eth10_in_bytes = `net.if.in[eth10_bytes]`)
trend <- trend %>% rename(eth11_in_bytes = `net.if.in[eth11_bytes]`)

trend <- trend %>% rename(eth0_out_bytes = `net.if.out[eth0_bytes]`)
trend <- trend %>% rename(eth1_out_bytes = `net.if.out[eth1_bytes]`)
trend <- trend %>% rename(eth2_out_bytes = `net.if.out[eth2_bytes]`)
trend <- trend %>% rename(eth3_out_bytes = `net.if.out[eth3_bytes]`)
trend <- trend %>% rename(eth4_out_bytes = `net.if.out[eth4_bytes]`)
trend <- trend %>% rename(eth5_out_bytes = `net.if.out[eth5_bytes]`)
trend <- trend %>% rename(eth6_out_bytes = `net.if.out[eth6_bytes]`)
trend <- trend %>% rename(eth7_out_bytes = `net.if.out[eth7_bytes]`)
trend <- trend %>% rename(eth8_out_bytes = `net.if.out[eth8_bytes]`)
trend <- trend %>% rename(eth9_out_bytes = `net.if.out[eth9_bytes]`)
trend <- trend %>% rename(eth10_out_bytes = `net.if.out[eth10_bytes]`)
trend <- trend %>% rename(eth11_out_bytes = `net.if.out[eth11_bytes]`)

trend <- trend %>% rename(eth0_in_bytes_std = `net.if.in[eth0_bytes]_std`)
trend <- trend %>% rename(eth1_in_bytes_std = `net.if.in[eth1_bytes]_std`)
trend <- trend %>% rename(eth2_in_bytes_std = `net.if.in[eth2_bytes]_std`)
trend <- trend %>% rename(eth3_in_bytes_std = `net.if.in[eth3_bytes]_std`)
trend <- trend %>% rename(eth4_in_bytes_std = `net.if.in[eth4_bytes]_std`)
trend <- trend %>% rename(eth5_in_bytes_std = `net.if.in[eth5_bytes]_std`)
trend <- trend %>% rename(eth6_in_bytes_std = `net.if.in[eth6_bytes]_std`)
trend <- trend %>% rename(eth7_in_bytes_std = `net.if.in[eth7_bytes]_std`)
trend <- trend %>% rename(eth8_in_bytes_std = `net.if.in[eth8_bytes]_std`)
trend <- trend %>% rename(eth9_in_bytes_std = `net.if.in[eth9_bytes]_std`)
trend <- trend %>% rename(eth10_in_bytes_std = `net.if.in[eth10_bytes]_std`)
trend <- trend %>% rename(eth11_in_bytes_std = `net.if.in[eth11_bytes]_std`)

trend <- trend %>% rename(eth0_out_bytes_std = `net.if.out[eth0_bytes]_std`)
trend <- trend %>% rename(eth1_out_bytes_std = `net.if.out[eth1_bytes]_std`)
trend <- trend %>% rename(eth2_out_bytes_std = `net.if.out[eth2_bytes]_std`)
trend <- trend %>% rename(eth3_out_bytes_std = `net.if.out[eth3_bytes]_std`)
trend <- trend %>% rename(eth4_out_bytes_std = `net.if.out[eth4_bytes]_std`)
trend <- trend %>% rename(eth5_out_bytes_std = `net.if.out[eth5_bytes]_std`)
trend <- trend %>% rename(eth6_out_bytes_std = `net.if.out[eth6_bytes]_std`)
trend <- trend %>% rename(eth7_out_bytes_std = `net.if.out[eth7_bytes]_std`)
trend <- trend %>% rename(eth8_out_bytes_std = `net.if.out[eth8_bytes]_std`)
trend <- trend %>% rename(eth9_out_bytes_std = `net.if.out[eth9_bytes]_std`)
trend <- trend %>% rename(eth10_out_bytes_std = `net.if.out[eth10_bytes]_std`)
trend <- trend %>% rename(eth11_out_bytes_std = `net.if.out[eth11_bytes]_std`)

trend <- trend %>% rename(eth0_in_bytes_min = `net.if.in[eth0_bytes]_min`)
trend <- trend %>% rename(eth1_in_bytes_min = `net.if.in[eth1_bytes]_min`)
trend <- trend %>% rename(eth2_in_bytes_min = `net.if.in[eth2_bytes]_min`)
trend <- trend %>% rename(eth3_in_bytes_min = `net.if.in[eth3_bytes]_min`)
trend <- trend %>% rename(eth4_in_bytes_min = `net.if.in[eth4_bytes]_min`)
trend <- trend %>% rename(eth5_in_bytes_min = `net.if.in[eth5_bytes]_min`)
trend <- trend %>% rename(eth6_in_bytes_min = `net.if.in[eth6_bytes]_min`)
trend <- trend %>% rename(eth7_in_bytes_min = `net.if.in[eth7_bytes]_min`)
trend <- trend %>% rename(eth8_in_bytes_min = `net.if.in[eth8_bytes]_min`)
trend <- trend %>% rename(eth9_in_bytes_min = `net.if.in[eth9_bytes]_min`)
trend <- trend %>% rename(eth10_in_bytes_min = `net.if.in[eth10_bytes]_min`)
trend <- trend %>% rename(eth11_in_bytes_min = `net.if.in[eth11_bytes]_min`)

trend <- trend %>% rename(eth0_out_bytes_min = `net.if.out[eth0_bytes]_min`)
trend <- trend %>% rename(eth1_out_bytes_min = `net.if.out[eth1_bytes]_min`)
trend <- trend %>% rename(eth2_out_bytes_min = `net.if.out[eth2_bytes]_min`)
trend <- trend %>% rename(eth3_out_bytes_min = `net.if.out[eth3_bytes]_min`)
trend <- trend %>% rename(eth4_out_bytes_min = `net.if.out[eth4_bytes]_min`)
trend <- trend %>% rename(eth5_out_bytes_min = `net.if.out[eth5_bytes]_min`)
trend <- trend %>% rename(eth6_out_bytes_min = `net.if.out[eth6_bytes]_min`)
trend <- trend %>% rename(eth7_out_bytes_min = `net.if.out[eth7_bytes]_min`)
trend <- trend %>% rename(eth8_out_bytes_min = `net.if.out[eth8_bytes]_min`)
trend <- trend %>% rename(eth9_out_bytes_min = `net.if.out[eth9_bytes]_min`)
trend <- trend %>% rename(eth10_out_bytes_min = `net.if.out[eth10_bytes]_min`)
trend <- trend %>% rename(eth11_out_bytes_min = `net.if.out[eth11_bytes]_min`)

trend <- trend %>% rename(eth0_in_bytes_max = `net.if.in[eth0_bytes]_max`)
trend <- trend %>% rename(eth1_in_bytes_max = `net.if.in[eth1_bytes]_max`)
trend <- trend %>% rename(eth2_in_bytes_max = `net.if.in[eth2_bytes]_max`)
trend <- trend %>% rename(eth3_in_bytes_max = `net.if.in[eth3_bytes]_max`)
trend <- trend %>% rename(eth4_in_bytes_max = `net.if.in[eth4_bytes]_max`)
trend <- trend %>% rename(eth5_in_bytes_max = `net.if.in[eth5_bytes]_max`)
trend <- trend %>% rename(eth6_in_bytes_max = `net.if.in[eth6_bytes]_max`)
trend <- trend %>% rename(eth7_in_bytes_max = `net.if.in[eth7_bytes]_max`)
trend <- trend %>% rename(eth8_in_bytes_max = `net.if.in[eth8_bytes]_max`)
trend <- trend %>% rename(eth9_in_bytes_max = `net.if.in[eth9_bytes]_max`)
trend <- trend %>% rename(eth10_in_bytes_max = `net.if.in[eth10_bytes]_max`)
trend <- trend %>% rename(eth11_in_bytes_max = `net.if.in[eth11_bytes]_max`)

trend <- trend %>% rename(eth0_out_bytes_max = `net.if.out[eth0_bytes]_max`)
trend <- trend %>% rename(eth1_out_bytes_max = `net.if.out[eth1_bytes]_max`)
trend <- trend %>% rename(eth2_out_bytes_max = `net.if.out[eth2_bytes]_max`)
trend <- trend %>% rename(eth3_out_bytes_max = `net.if.out[eth3_bytes]_max`)
trend <- trend %>% rename(eth4_out_bytes_max = `net.if.out[eth4_bytes]_max`)
trend <- trend %>% rename(eth5_out_bytes_max = `net.if.out[eth5_bytes]_max`)
trend <- trend %>% rename(eth6_out_bytes_max = `net.if.out[eth6_bytes]_max`)
trend <- trend %>% rename(eth7_out_bytes_max = `net.if.out[eth7_bytes]_max`)
trend <- trend %>% rename(eth8_out_bytes_max = `net.if.out[eth8_bytes]_max`)
trend <- trend %>% rename(eth9_out_bytes_max = `net.if.out[eth9_bytes]_max`)
trend <- trend %>% rename(eth10_out_bytes_max = `net.if.out[eth10_bytes]_max`)
trend <- trend %>% rename(eth11_out_bytes_max = `net.if.out[eth11_bytes]_max`)

trend <- trend %>% rename(eth0_in_packets = `net.if.in[eth0_packets]`)
trend <- trend %>% rename(eth1_in_packets = `net.if.in[eth1_packets]`)
trend <- trend %>% rename(eth2_in_packets = `net.if.in[eth2_packets]`)
trend <- trend %>% rename(eth3_in_packets = `net.if.in[eth3_packets]`)
trend <- trend %>% rename(eth4_in_packets = `net.if.in[eth4_packets]`)
trend <- trend %>% rename(eth5_in_packets = `net.if.in[eth5_packets]`)
trend <- trend %>% rename(eth6_in_packets = `net.if.in[eth6_packets]`)
trend <- trend %>% rename(eth7_in_packets = `net.if.in[eth7_packets]`)
trend <- trend %>% rename(eth8_in_packets = `net.if.in[eth8_packets]`)
trend <- trend %>% rename(eth9_in_packets = `net.if.in[eth9_packets]`)
trend <- trend %>% rename(eth10_in_packets = `net.if.in[eth10_packets]`)
trend <- trend %>% rename(eth11_in_packets = `net.if.in[eth11_packets]`)

trend <- trend %>% rename(eth0_out_packets = `net.if.out[eth0_packets]`)
trend <- trend %>% rename(eth1_out_packets = `net.if.out[eth1_packets]`)
trend <- trend %>% rename(eth2_out_packets = `net.if.out[eth2_packets]`)
trend <- trend %>% rename(eth3_out_packets = `net.if.out[eth3_packets]`)
trend <- trend %>% rename(eth4_out_packets = `net.if.out[eth4_packets]`)
trend <- trend %>% rename(eth5_out_packets = `net.if.out[eth5_packets]`)
trend <- trend %>% rename(eth6_out_packets = `net.if.out[eth6_packets]`)
trend <- trend %>% rename(eth7_out_packets = `net.if.out[eth7_packets]`)
trend <- trend %>% rename(eth8_out_packets = `net.if.out[eth8_packets]`)
trend <- trend %>% rename(eth9_out_packets = `net.if.out[eth9_packets]`)
trend <- trend %>% rename(eth10_out_packets = `net.if.out[eth10_packets]`)
trend <- trend %>% rename(eth11_out_packets = `net.if.out[eth11_packets]`)

trend <- trend %>% rename(eth0_in_packets_std = `net.if.in[eth0_packets]_std`)
trend <- trend %>% rename(eth1_in_packets_std = `net.if.in[eth1_packets]_std`)
trend <- trend %>% rename(eth2_in_packets_std = `net.if.in[eth2_packets]_std`)
trend <- trend %>% rename(eth3_in_packets_std = `net.if.in[eth3_packets]_std`)
trend <- trend %>% rename(eth4_in_packets_std = `net.if.in[eth4_packets]_std`)
trend <- trend %>% rename(eth5_in_packets_std = `net.if.in[eth5_packets]_std`)
trend <- trend %>% rename(eth6_in_packets_std = `net.if.in[eth6_packets]_std`)
trend <- trend %>% rename(eth7_in_packets_std = `net.if.in[eth7_packets]_std`)
trend <- trend %>% rename(eth8_in_packets_std = `net.if.in[eth8_packets]_std`)
trend <- trend %>% rename(eth9_in_packets_std = `net.if.in[eth9_packets]_std`)
trend <- trend %>% rename(eth10_in_packets_std = `net.if.in[eth10_packets]_std`)
trend <- trend %>% rename(eth11_in_packets_std = `net.if.in[eth11_packets]_std`)

trend <- trend %>% rename(eth0_out_packets_std = `net.if.out[eth0_packets]_std`)
trend <- trend %>% rename(eth1_out_packets_std = `net.if.out[eth1_packets]_std`)
trend <- trend %>% rename(eth2_out_packets_std = `net.if.out[eth2_packets]_std`)
trend <- trend %>% rename(eth3_out_packets_std = `net.if.out[eth3_packets]_std`)
trend <- trend %>% rename(eth4_out_packets_std = `net.if.out[eth4_packets]_std`)
trend <- trend %>% rename(eth5_out_packets_std = `net.if.out[eth5_packets]_std`)
trend <- trend %>% rename(eth6_out_packets_std = `net.if.out[eth6_packets]_std`)
trend <- trend %>% rename(eth7_out_packets_std = `net.if.out[eth7_packets]_std`)
trend <- trend %>% rename(eth8_out_packets_std = `net.if.out[eth8_packets]_std`)
trend <- trend %>% rename(eth9_out_packets_std = `net.if.out[eth9_packets]_std`)
trend <- trend %>% rename(eth10_out_packets_std = `net.if.out[eth10_packets]_std`)
trend <- trend %>% rename(eth11_out_packets_std = `net.if.out[eth11_packets]_std`)

trend <- trend %>% rename(eth0_in_packets_min = `net.if.in[eth0_packets]_min`)
trend <- trend %>% rename(eth1_in_packets_min = `net.if.in[eth1_packets]_min`)
trend <- trend %>% rename(eth2_in_packets_min = `net.if.in[eth2_packets]_min`)
trend <- trend %>% rename(eth3_in_packets_min = `net.if.in[eth3_packets]_min`)
trend <- trend %>% rename(eth4_in_packets_min = `net.if.in[eth4_packets]_min`)
trend <- trend %>% rename(eth5_in_packets_min = `net.if.in[eth5_packets]_min`)
trend <- trend %>% rename(eth6_in_packets_min = `net.if.in[eth6_packets]_min`)
trend <- trend %>% rename(eth7_in_packets_min = `net.if.in[eth7_packets]_min`)
trend <- trend %>% rename(eth8_in_packets_min = `net.if.in[eth8_packets]_min`)
trend <- trend %>% rename(eth9_in_packets_min = `net.if.in[eth9_packets]_min`)
trend <- trend %>% rename(eth10_in_packets_min = `net.if.in[eth10_packets]_min`)
trend <- trend %>% rename(eth11_in_packets_min = `net.if.in[eth11_packets]_min`)

trend <- trend %>% rename(eth0_out_packets_min = `net.if.out[eth0_packets]_min`)
trend <- trend %>% rename(eth1_out_packets_min = `net.if.out[eth1_packets]_min`)
trend <- trend %>% rename(eth2_out_packets_min = `net.if.out[eth2_packets]_min`)
trend <- trend %>% rename(eth3_out_packets_min = `net.if.out[eth3_packets]_min`)
trend <- trend %>% rename(eth4_out_packets_min = `net.if.out[eth4_packets]_min`)
trend <- trend %>% rename(eth5_out_packets_min = `net.if.out[eth5_packets]_min`)
trend <- trend %>% rename(eth6_out_packets_min = `net.if.out[eth6_packets]_min`)
trend <- trend %>% rename(eth7_out_packets_min = `net.if.out[eth7_packets]_min`)
trend <- trend %>% rename(eth8_out_packets_min = `net.if.out[eth8_packets]_min`)
trend <- trend %>% rename(eth9_out_packets_min = `net.if.out[eth9_packets]_min`)
trend <- trend %>% rename(eth10_out_packets_min = `net.if.out[eth10_packets]_min`)
trend <- trend %>% rename(eth11_out_packets_min = `net.if.out[eth11_packets]_min`)

trend <- trend %>% rename(eth0_in_packets_max = `net.if.in[eth0_packets]_max`)
trend <- trend %>% rename(eth1_in_packets_max = `net.if.in[eth1_packets]_max`)
trend <- trend %>% rename(eth2_in_packets_max = `net.if.in[eth2_packets]_max`)
trend <- trend %>% rename(eth3_in_packets_max = `net.if.in[eth3_packets]_max`)
trend <- trend %>% rename(eth4_in_packets_max = `net.if.in[eth4_packets]_max`)
trend <- trend %>% rename(eth5_in_packets_max = `net.if.in[eth5_packets]_max`)
trend <- trend %>% rename(eth6_in_packets_max = `net.if.in[eth6_packets]_max`)
trend <- trend %>% rename(eth7_in_packets_max = `net.if.in[eth7_packets]_max`)
trend <- trend %>% rename(eth8_in_packets_max = `net.if.in[eth8_packets]_max`)
trend <- trend %>% rename(eth9_in_packets_max = `net.if.in[eth9_packets]_max`)
trend <- trend %>% rename(eth10_in_packets_max = `net.if.in[eth10_packets]_max`)
trend <- trend %>% rename(eth11_in_packets_max = `net.if.in[eth11_packets]_max`)

trend <- trend %>% rename(eth0_out_packets_max = `net.if.out[eth0_packets]_max`)
trend <- trend %>% rename(eth1_out_packets_max = `net.if.out[eth1_packets]_max`)
trend <- trend %>% rename(eth2_out_packets_max = `net.if.out[eth2_packets]_max`)
trend <- trend %>% rename(eth3_out_packets_max = `net.if.out[eth3_packets]_max`)
trend <- trend %>% rename(eth4_out_packets_max = `net.if.out[eth4_packets]_max`)
trend <- trend %>% rename(eth5_out_packets_max = `net.if.out[eth5_packets]_max`)
trend <- trend %>% rename(eth6_out_packets_max = `net.if.out[eth6_packets]_max`)
trend <- trend %>% rename(eth7_out_packets_max = `net.if.out[eth7_packets]_max`)
trend <- trend %>% rename(eth8_out_packets_max = `net.if.out[eth8_packets]_max`)
trend <- trend %>% rename(eth9_out_packets_max = `net.if.out[eth9_packets]_max`)
trend <- trend %>% rename(eth10_out_packets_max = `net.if.out[eth10_packets]_max`)
trend <- trend %>% rename(eth11_out_packets_max = `net.if.out[eth11_packets]_max`)

trend <- trend %>% rename(power_CPU = `sensor.power[CPU core]`)
trend <- trend %>% rename(power_VCore = `sensor.power[VCore]`)
trend <- trend %>% rename(power_VCore1 = `sensor.power[VCore 1]`)
trend <- trend %>% rename(temp_CPU = `sensor.temp[CPU Temp]`)
trend <- trend %>% rename(temp_SYS = `sensor.temp[Sys Temp]`)
trend <- trend %>% rename(temp_AUX = `sensor.temp[AUX Temp]`)
trend <- trend %>% rename(temp_MB = `sensor.temp[M/B Temp]`)
trend <- trend %>% rename(temp_Core0 = `sensor.temp[Core 0]`)
trend <- trend %>% rename(temp_Core1 = `sensor.temp[Core 1]`)
trend <- trend %>% rename(temp_1 = `sensor.temp[temp1]`)
trend <- trend %>% rename(temp_2 = `sensor.temp[temp2]`)
trend <- trend %>% rename(temp_3 = `sensor.temp[temp3]`)
trend <- trend %>% rename(fan_AUX = `sensor.fan[Aux Fan]`)
trend <- trend %>% rename(fan_Case = `sensor.fan[Case Fan]`)
trend <- trend %>% rename(fan_CPU = `sensor.fan[CPU Fan]`)
trend <- trend %>% rename(fan_PS = `sensor.fan[P/S Fan]`)
trend <- trend %>% rename(fan_1 = `sensor.fan[fan1]`)
trend <- trend %>% rename(fan_2 = `sensor.fan[fan2]`)
trend <- trend %>% rename(fan_3 = `sensor.fan[fan3]`)
trend <- trend %>% rename(fan_4 = `sensor.fan[fan4]`)

trend <- trend %>% rename(power_CPU_std = `sensor.power[CPU core]_std`)
trend <- trend %>% rename(power_VCore_std = `sensor.power[VCore]_std`)
trend <- trend %>% rename(power_VCore1_std = `sensor.power[VCore 1]_std`)
trend <- trend %>% rename(temp_CPU_std = `sensor.temp[CPU Temp]_std`)
trend <- trend %>% rename(temp_SYS_std = `sensor.temp[Sys Temp]_std`)
trend <- trend %>% rename(temp_AUX_std = `sensor.temp[AUX Temp]_std`)
trend <- trend %>% rename(temp_MB_std = `sensor.temp[M/B Temp]_std`)
trend <- trend %>% rename(temp_Core0_std = `sensor.temp[Core 0]_std`)
trend <- trend %>% rename(temp_Core1_std = `sensor.temp[Core 1]_std`)
trend <- trend %>% rename(temp_1_std = `sensor.temp[temp1]_std`)
trend <- trend %>% rename(temp_2_std = `sensor.temp[temp2]_std`)
trend <- trend %>% rename(temp_3_std = `sensor.temp[temp3]_std`)
trend <- trend %>% rename(fan_AUX_std = `sensor.fan[Aux Fan]_std`)
trend <- trend %>% rename(fan_Case_std = `sensor.fan[Case Fan]_std`)
trend <- trend %>% rename(fan_CPU_std = `sensor.fan[CPU Fan]_std`)
trend <- trend %>% rename(fan_PS_std = `sensor.fan[P/S Fan]_std`)
trend <- trend %>% rename(fan_1_std = `sensor.fan[fan1]_std`)
trend <- trend %>% rename(fan_2_std = `sensor.fan[fan2]_std`)
trend <- trend %>% rename(fan_3_std = `sensor.fan[fan3]_std`)
trend <- trend %>% rename(fan_4_std = `sensor.fan[fan4]_std`)

trend <- trend %>% rename(power_CPU_min = `sensor.power[CPU core]_min`)
trend <- trend %>% rename(power_VCore_min = `sensor.power[VCore]_min`)
trend <- trend %>% rename(power_VCore1_min = `sensor.power[VCore 1]_min`)
trend <- trend %>% rename(temp_CPU_min = `sensor.temp[CPU Temp]_min`)
trend <- trend %>% rename(temp_SYS_min = `sensor.temp[Sys Temp]_min`)
trend <- trend %>% rename(temp_AUX_min = `sensor.temp[AUX Temp]_min`)
trend <- trend %>% rename(temp_MB_min = `sensor.temp[M/B Temp]_min`)
trend <- trend %>% rename(temp_Core0_min = `sensor.temp[Core 0]_min`)
trend <- trend %>% rename(temp_Core1_min = `sensor.temp[Core 1]_min`)
trend <- trend %>% rename(temp_1_min = `sensor.temp[temp1]_min`)
trend <- trend %>% rename(temp_2_min = `sensor.temp[temp2]_min`)
trend <- trend %>% rename(temp_3_min = `sensor.temp[temp3]_min`)
trend <- trend %>% rename(fan_AUX_min = `sensor.fan[Aux Fan]_min`)
trend <- trend %>% rename(fan_Case_min = `sensor.fan[Case Fan]_min`)
trend <- trend %>% rename(fan_CPU_min = `sensor.fan[CPU Fan]_min`)
trend <- trend %>% rename(fan_PS_min = `sensor.fan[P/S Fan]_min`)
trend <- trend %>% rename(fan_1_min = `sensor.fan[fan1]_min`)
trend <- trend %>% rename(fan_2_min = `sensor.fan[fan2]_min`)
trend <- trend %>% rename(fan_3_min = `sensor.fan[fan3]_min`)
trend <- trend %>% rename(fan_4_min = `sensor.fan[fan4]_min`)

trend <- trend %>% rename(power_CPU_max = `sensor.power[CPU core]_max`)
trend <- trend %>% rename(power_VCore_max = `sensor.power[VCore]_max`)
trend <- trend %>% rename(power_VCore1_max = `sensor.power[VCore 1]_max`)
trend <- trend %>% rename(temp_CPU_max = `sensor.temp[CPU Temp]_max`)
trend <- trend %>% rename(temp_SYS_max = `sensor.temp[Sys Temp]_max`)
trend <- trend %>% rename(temp_AUX_max = `sensor.temp[AUX Temp]_max`)
trend <- trend %>% rename(temp_MB_max = `sensor.temp[M/B Temp]_max`)
trend <- trend %>% rename(temp_Core0_max = `sensor.temp[Core 0]_max`)
trend <- trend %>% rename(temp_Core1_max = `sensor.temp[Core 1]_max`)
trend <- trend %>% rename(temp_1_max = `sensor.temp[temp1]_max`)
trend <- trend %>% rename(temp_2_max = `sensor.temp[temp2]_max`)
trend <- trend %>% rename(temp_3_max = `sensor.temp[temp3]_max`)
trend <- trend %>% rename(fan_AUX_max = `sensor.fan[Aux Fan]_max`)
trend <- trend %>% rename(fan_Case_max = `sensor.fan[Case Fan]_max`)
trend <- trend %>% rename(fan_CPU_max = `sensor.fan[CPU Fan]_max`)
trend <- trend %>% rename(fan_PS_max = `sensor.fan[P/S Fan]_max`)
trend <- trend %>% rename(fan_1_max = `sensor.fan[fan1]_max`)
trend <- trend %>% rename(fan_2_max = `sensor.fan[fan2]_max`)
trend <- trend %>% rename(fan_3_max = `sensor.fan[fan3]_max`)
trend <- trend %>% rename(fan_4_max = `sensor.fan[fan4]_max`)

z <- as.data.table(full_join(x,t,by="Hostname"))
y<- z %>% filter(`net.if.in[eth0_bytes]`>0) %>% filter(!is.na(Model))
#index <- sample(nrow(y),300)
#y.test <- y[index,]
#y.train <- y[-index,]
#y.classifier <- ksvm(Model ~ ., data = y.train, kernel = "vanilladot")

lme4
pbkrtest
car
