library("data.table")
library("dplyr")
library("ggplot2")
library("stringr")
setwd("~/IDS2016/trigger")
x <- rbindlist( lapply(list.files(pattern = "trigger-2016[0-1][0-9].csv"), fread))
setnames(x,c("Date","Hostname","Description"))
x$Date <- as.Date(x$Date,format="%Y-%m-%d %H:%M:%S")
x$Description <- str_replace(x$Description, " on .* is", " is")
x$Description <- str_replace(x$Description, " on .*$", "")
x$Description <- str_replace(x$Description, " .* has ", " has ")
x$Description <- str_replace(x$Description, ".* has just been restarted", "restarted")
x$Description <- str_replace(x$Description, "available memory.*$", "available memory")
x$Description <- str_replace(x$Description, "VPN UP .*", "VPN UP")
x$Description <- str_replace(x$Description, "VPN DOWN .*", "VPN DOWN")
x$Description <- str_replace(x$Description, "VPN tun[0-9]* ", "VPN ")
x$Description <- str_replace(x$Description, "VPN tap[0-9]* ", "VPN ")
x$Description <- str_replace(x$Description, "Too high temp.*", "Too high temp")
x$Description <- str_replace(x$Description, "Too low fan speed.*", "Too low fan speed")

daily_desc<- as.data.table(x %>% group_by(Date,Description) %>% summarize(n = n()))
daily_desc %>% filter(Date == "2016-11-09") %>% arrange(-n)
daily_desc %>% filter(Date == "2016-03-30") %>% arrange(-n)
daily_desc %>% filter(Date == "2016-08-16") %>% arrange(-n)

zabbix <- daily_desc %>% filter(Description %like% "Zabbix")
g <- ggplot ( zabbix, aes (x = Date, y = n))
g <- g + geom_bar(stat = "identity")
plot(g)

clock <- daily_desc %>% filter(Description %like% "Clock")
g <- ggplot ( clock, aes (x = Date, y = n))
g <- g + geom_bar(stat = "identity")
plot(g)

massive <- daily_desc %>% filter(n>50)
g <- ggplot ( massive, aes (x = Date, y = n, fill = Description))
g <- g + geom_bar(stat = "identity")
plot(g)
massive
